### ISSUE TITLE
does it support oracle

### ISSUE THREAD

**Issue by aghasemiN** [NorthernLight1/N.EntityFrameworkCore.Extensions#29]
hi, It is not clear which database this package supports , is that oracle supported because I am getting error under oracle

**Comment by NorthernLight1** [comment]
This package only supports SQL Server and there are no plans to support Oracle.

**Comment by NorthernLight1** [comment]
@aghasemiN 

We now support MySql using [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql)
