### ISSUE TITLE
Id empty error in BulkInsert

### ISSUE THREAD

**Issue by aligholipour** [NorthernLight1/N.EntityFrameworkCore.Extensions#31]
Hi. The ID field in the database is either NEWID or GUID. When I use BulkInsert, it gives the following error:

"Cannot insert the value NULL into column 'Id'."

It doesn't matter whether I fill the Id in my model or not; it gives this error anyway.

**Comment by NorthernLight1** [comment]
This bug was addressed in v6.0.8.5.
