### ISSUE TITLE
BulkMergeAsync Not Updating the datetime field if its created with default value GetDate()

### ISSUE THREAD

**Issue by sathishmohan-ps** [NorthernLight1/N.EntityFrameworkCore.Extensions#35]
BulkMergeAsync Not Updating the datetime field if its created with default value GetDate()

**Comment by NorthernLight1** [comment]
@sathishmohan-ps 

This issue was fixed in v6.0.8.5. I confirmed that the test cases for BulkMergeAsync() have a database generated field and it works as expected. Please give me more information about this issue so I can look into it.

**Comment by sathishmohan-ps** [comment]
I am using the latest version. Only insert scenario its working, still a problem for update.

**Comment by NorthernLight1** [comment]
@sathishmohan-ps

Thanks for reporting this issue, it has been resolved in v7.0.13.2
