### ISSUE TITLE
MIT or GPL license?

### ISSUE THREAD

**Issue by allen-yh-chan** [NorthernLight1/N.EntityFrameworkCore.Extensions#36]
May I confirm whether the license is under MIT or GPL? I noticed MIT is specified in https://www.nuget.org/packages/N.EntityFrameworkCore.Extensions/6.0.8.1, but GPL is mentioned on GitHub.

**Comment by NorthernLight1** [comment]
The license has been changed to MIT as it should have been when this project was started.
