### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by ABIOLI-COM** [NorthernLight1/N.EntityFrameworkCore.Extensions#37]
I'm using .NET 8, and while trying to execute a method from the library, I get a MissingMethodException, that in theory should be due to a conflict in versions.  
I checked my project, and everything is aligned to 8.0.0 (including the dependencies for N.EntityFrameworkCore.Extensions).  
Is there any known issues about compatibility with .NET 8, or am I just missing something?
Thank you
Andrea

**Comment by NorthernLight1** [comment]
@ABIOLI-COM,

Thanks for reporting this issue. It has been resolved in v8.0.02.
