### ISSUE TITLE
Support bulk insert on tables with triggers

### ISSUE THREAD

**Issue by kragoth** [NorthernLight1/N.EntityFrameworkCore.Extensions#51]
**Is your feature request related to a problem? Please describe.**

BulkInsert does not support inserting into tables that have triggers.
The sql generated for bulk insert is basically
```
MERGE [schema].[table] AS t USING [schema].[#tmp_tbl_name] AS s 
ON 1=2 WHEN NOT MATCHED THEN INSERT ([col1],[col2]) 
OUTPUT $Action,[s].[_be_xx_id],[inserted].[Id],[inserted].[RowVer],[inserted].[TemporalEndTime],[inserted].[TemporalStartTime] ;
```

This results in the error: `The target table 't' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.`

**Describe the solution you'd like**
Given the following discussions in EF around the topic: https://github.com/dotnet/efcore/issues/27372 
and on stackoverflow: https://stackoverflow.com/questions/13198476/cannot-use-update-with-output-clause-when-a-trigger-is-on-the-table

It seems that the only solution would be to generate an alternative insert statement if the table has a trigger.

**Describe alternatives you've considered**
I have used ZEntityFramework.Plus to do bulk inserts successfully. So I assume that they are not using the merge statement. But, it was a while ago and so I'm not 100% sure it was on a table with a trigger. I would need to go test it out.

**Comment by kragoth** [comment]
@NorthernLight1 yeah if the output is not mandatory then yeah, that would be a great fix. What's the effect of removing the output?

**Comment by NorthernLight1** [comment]
Kragoth,

The output is used to set any database generated fields, like an Id or CreatedDate fields, but it does result in a small performance overhead.

**Comment by kragoth** [comment]
@NorthernLight1 legend! We'll give it a go. :)

**Comment by kragoth** [comment]
@NorthernLight1 unfortunately that doesn't work. It seems to be because of [this line of code](https://github.com/NorthernLight1/N.EntityFrameworkCore.Extensions/blob/a0ae30d6c2f1d6ba841bd8503429f6177f2ef6d3/N.EntityFrameworkCore.Extensions/Data/BulkOperationAsync.cs#L45)

```
                var columnsToOutput = GetMergeOutputColumns(autoGeneratedColumns, delete);
```

This always adds Action and Id to the output columns so an output statement is *always* added to the sql command.

**Comment by NorthernLight1** [comment]
kragoth

I will release another version soon and patch it.

**Comment by NorthernLight1** [comment]
kragoth,

Please try again with 8.0.0.7. The issue should be resolved.

**Comment by kragoth** [comment]
@NorthernLight1 this is working for us now. Thank you!

**Comment by awaais78** [comment]
I am using version N.EntityFrameworkCore.Extensions 8.0.0.12 and i am facing the same issue . As my requirement is 
i need entities to be filled with auto-generated ID from database.
i need to fire trigger on BulkInsert as well.

await _context.BulkInsertAsync(entities,
    new BulkInsertOptions<TableName>
    {
        AutoMapOutput = true,
        CommandTimeout = 0,
        KeepIdentity = true,                    
    });

**Comment by kragoth** [comment]
> I am using version N.EntityFrameworkCore.Extensions 8.0.0.12 and i am facing the same issue . As my requirement is i need entities to be filled with auto-generated ID from database. i need to fire trigger on BulkInsert as well.
> 
> await _context.BulkInsertAsync(entities, new BulkInsertOptions { AutoMapOutput = true, CommandTimeout = 0, KeepIdentity = true, });

As per the comments above you can't fire a trigger *and* have output on a bulk insert.
You will need to re-query your inserted entities from the database after the bulk insert is done. Use some sort of descriminator column "eg" batchId that has the same GUID for each bulkInsert operation. Then query out all entities with your expected batchId. This will give you all entities with their Ids etc.
