### ISSUE TITLE
Add support for Entity Graph to Bulk Insert.

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [NorthernLight1/N.EntityFrameworkCore.Extensions#81]
**Is your feature request related to a problem? Please describe.**
It is quite challenging when there is a complex relationship between entities to get all of the PK->FK correct, and a large part of this is doing the insets "in the right order" as well as post-patching certain things..

**Describe the solution you'd like**

**Describe alternatives you've considered**
Using a regular DbContext and DbSets with single operations works using standard EF.

**Additional context**
Other (paid) extensions seem to have this capabilitity..

**Comment by NorthernLight1** [comment]
@davidcorbin-atmosera,

The lack of graph support for all bulk operations was intentional because amount of work involved with adding that feature, though it could be considered in the future. 

I will keep this issue open as I evaluate the amount of effort to implement this feature.

**Comment by davidcorbin-atmosera** [comment]
Yeah, quite a bit.... the gotcha [just as an FYI] is I am migrating a very old and very slow system. So much of the time is in "one by one" but at the same time modifications transcend an object graph of about 40 different types, and no clear order in which to bulk save (I am not sure there is one directed-graph that covers all bases, it is easy to get lost)...
