### ISSUE TITLE
Exception in BulkMerge when using composite primary key

### ISSUE THREAD

**Issue by osmozis** [NorthernLight1/N.EntityFrameworkCore.Extensions#85]
dbContext.BulkMerge() method generates exception "Unable to drop table '#tmp_be_xx...' because it doesn't exist or you don't have permissions"

This kind of exception only thrown in case of using composite primary key as in 
`modelBuilder.Entity<Example>()`
`   .Property(x => x.Key1)`
`   .Property(x => x.Key2)`
`   .HasKey(x => new { x.Key1, x.Key2 })`

The problem happens due to wrong SQL code generated for the MERGE query
`MERGE [Example] AS t USING [#tmp_be_xx_Example] AS s ON t.Key1=s.Key1ANDt.Key2=s.Key2......` <- there are no spaces around 'AND' keyword

There are actually 2 exceptions: 
-first exception is about wrong SQL statement, but it is being swallowed by the library 
-the second one is about temp table dropping error that happens during BulkOperation.Dispose

**Comment by Jackobii** [comment]
I'm encountering the same issue. When using composite keys the GetJoinConditionSql in CommonUtil.cs will add "AND" without any spaces when building the query. 

Compare this to the same method in the N.EntityFramework.Extensions where it will instead add " AND " with spaces. 
N.EntityFrameworkCore.Extensions: 
![{2169A04B-B698-40F4-A71D-57BE77596A2A}](https://github.com/user-attachments/assets/95dbda2a-ce61-41e5-979f-e973b27b4914)
N.EntityFramework.Extensions: 
![{3324EAA5-7930-4993-B5C9-80829164B751}](https://github.com/user-attachments/assets/581796a1-65a5-4a53-901c-6200396a3666)

Hopefully that should be all thats needed to fix the issue 😄

**Comment by NorthernLight1** [comment]
[osmozis](https://github.com/osmozis), [Jackobi](https://github.com/Jackobii)

This issue has been addressed in 8.0.0.12

Please test it and let me know if you still have any issues.

**Comment by osmozis** [comment]
@NorthernLight1 , now it works like a charm. Thanks a lot
